### ISSUE TITLE
Build errors after installing library in UE4.19

### ISSUE THREAD

**Issue by pilotdave** [nialna/libnoise-UE4-ready#2]
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt.h(134): error C2953: '_CrtEnableIf<true,_Ty>': class template has already been defined
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(125): note: see declaration of '_CrtEnableIf<true,_Ty>'
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt.h(489): error C2011: '__crt_locale_data_public': 'struct' type redefinition
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(455): note: see declaration of '__crt_locale_data_public'
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt.h(496): error C2011: '__crt_locale_pointers': 'struct' type redefinition
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(462): note: see declaration of '__crt_locale_pointers'
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt.h(504): error C2011: '_Mbstatet': 'struct' type redefinition
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(470): note: see declaration of '_Mbstatet'

**Comment by pilotdave** [comment]
It seems like the .lib has the mfc libraries inside and the engine (or c++) also defines these, although they are coming with the .lib. 
How can i remove the mfc libs from the .lib?

**Comment by pilotdave** [comment]
i fixed it after building the whole unreal engine from source on my machine before compiling the library.

**Comment by anomotion-alistair** [comment]
Ran into a very similar issue - solution was just to clean/rebuild the project (didn't have to rebuild the engine)
